In [3]:
# Import Libraries
import pandas as pd
import numpy as np
from random import randint

In [6]:
data = pd.read_csv('xAPI-Edu-Data.csv')
data.head()

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   gender                    480 non-null    object
 1   NationalITy               480 non-null    object
 2   PlaceofBirth              480 non-null    object
 3   StageID                   480 non-null    object
 4   GradeID                   480 non-null    object
 5   SectionID                 480 non-null    object
 6   Topic                     480 non-null    object
 7   Semester                  480 non-null    object
 8   Relation                  480 non-null    object
 9   raisedhands               480 non-null    int64 
 10  VisITedResources          480 non-null    int64 
 11  AnnouncementsView         480 non-null    int64 
 12  Discussion                480 non-null    int64 
 13  ParentAnsweringSurvey     480 non-null    object
 14  ParentschoolSatisfaction  

In [9]:
df = data.drop(['gender', 'NationalITy', 'PlaceofBirth', 'StageID', 'Semester', 'Relation', 'raisedhands', 
                'VisITedResources', 'AnnouncementsView', 'Discussion', 'ParentAnsweringSurvey',
               'ParentschoolSatisfaction', 'ParentschoolSatisfaction', 'StudentAbsenceDays', 'Class'], axis = 1)
df.head()

GradeID SectionID Topic
0    G-04         A    IT
1    G-04         A    IT
2    G-04         A    IT
3    G-04         A    IT
4    G-04         A    IT

In [10]:
import random

n = np.random.randint(0, 10, 480)
df['score'] = n

In [11]:
df.head()

GradeID SectionID Topic  score
0    G-04         A    IT      2
1    G-04         A    IT      4
2    G-04         A    IT      2
3    G-04         A    IT      5
4    G-04         A    IT      4

In [14]:
x = df.iloc[:, :-1].values
x

array([['G-04', 'A', 'IT'],
       ['G-04', 'A', 'IT'],
       ['G-04', 'A', 'IT'],
       ...,
       ['G-08', 'A', 'Geology'],
       ['G-08', 'A', 'History'],
       ['G-08', 'A', 'History']], dtype=object)

In [45]:
type(x)

numpy.ndarray

In [47]:
x.shape(0)

TypeError: 'tuple' object is not callable

In [48]:
x[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [49]:
x = np.array(x)

In [50]:
x

array(<480x25 sparse matrix of type '<class 'numpy.float64'>'
	with 1440 stored elements in Compressed Sparse Row format>, dtype=object)

In [51]:
t = df.to_numpy()
t

array([['G-04', 'A', 'IT', 2],
       ['G-04', 'A', 'IT', 4],
       ['G-04', 'A', 'IT', 2],
       ...,
       ['G-08', 'A', 'Geology', 0],
       ['G-08', 'A', 'History', 0],
       ['G-08', 'A', 'History', 4]], dtype=object)

In [52]:
t.shape

(480, 4)

In [61]:
x = t[:, : -1]

In [62]:
x.shape

(480, 3)

In [18]:
y = df.iloc[:, -1].values
y

array([2, 4, 2, 5, 4, 8, 6, 7, 8, 7, 1, 3, 1, 7, 6, 6, 2, 3, 8, 4, 1, 8,
       2, 3, 8, 0, 6, 0, 8, 1, 5, 3, 5, 9, 3, 2, 8, 8, 7, 1, 2, 2, 8, 8,
       7, 3, 0, 8, 4, 1, 9, 1, 4, 4, 9, 7, 0, 8, 4, 0, 7, 6, 3, 5, 7, 3,
       4, 9, 2, 0, 0, 7, 1, 9, 2, 7, 3, 4, 1, 6, 4, 4, 0, 5, 8, 0, 5, 9,
       3, 1, 4, 3, 2, 5, 9, 0, 9, 8, 7, 7, 8, 5, 8, 0, 1, 5, 2, 6, 7, 2,
       0, 9, 1, 6, 2, 1, 4, 5, 8, 4, 3, 0, 7, 3, 8, 5, 8, 1, 9, 8, 7, 6,
       1, 6, 5, 6, 2, 0, 6, 5, 6, 4, 8, 4, 7, 3, 4, 3, 2, 0, 5, 2, 8, 9,
       2, 7, 7, 4, 6, 4, 1, 8, 7, 5, 0, 4, 6, 4, 0, 1, 1, 1, 4, 4, 7, 9,
       0, 1, 6, 1, 9, 4, 3, 7, 1, 0, 9, 5, 2, 0, 0, 7, 9, 8, 6, 3, 9, 3,
       7, 5, 5, 2, 5, 6, 5, 9, 4, 7, 1, 8, 1, 6, 7, 2, 7, 8, 6, 5, 8, 9,
       1, 0, 0, 6, 3, 9, 3, 5, 1, 0, 0, 2, 4, 9, 7, 2, 2, 9, 6, 8, 0, 6,
       9, 0, 3, 8, 8, 4, 3, 6, 1, 1, 9, 4, 4, 4, 1, 0, 4, 6, 3, 1, 0, 4,
       4, 6, 6, 9, 8, 4, 8, 2, 6, 6, 6, 5, 4, 4, 6, 4, 6, 0, 7, 7, 5, 2,
       2, 4, 8, 8, 3, 3, 3, 6, 7, 7, 8, 1, 7, 7, 0,

## Encode Categorical Data

### Encode Independent variable (x)

In [69]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
print(x.shape)
result = []
for i in range(0, 3):
    v = x[:, i]
    print(v.shape)
    #ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder())])
    one_hot_encoder = OneHotEncoder()
    v = v.reshape(1, -1)
    v = one_hot_encoder.fit_transform(v).toarray()
    #v = np.array(ct.fit_transform(v))
    result.append(v)

(480, 3)
(480,)
(480,)
(480,)


In [71]:
x

array([['G-04', 'A', 'IT'],
       ['G-04', 'A', 'IT'],
       ['G-04', 'A', 'IT'],
       ...,
       ['G-08', 'A', 'Geology'],
       ['G-08', 'A', 'History'],
       ['G-08', 'A', 'History']], dtype=object)

In [77]:
result = []# np.zeros((480, 3, 3))
for i in range(0, 3):
    v = x[:, i]
    print(v.shape)
    u, i = np.unique(v, return_inverse = True)
    v = np.eye(u.shape[0])[i]
    print(v.shape)
    result.append(v)

(480,)
(480, 10)
(480,)
(480, 3)
(480,)
(480, 12)


In [73]:
result

[array([[0., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        ...,
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])]

## Splitting the dataset (x = data, y = output) into the Training set and Test set

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(result, y, test_size = 0.2, random_state = 1)